//
//  ProjectsViewController.swift
//  TaskTracker2
//
//  Created by Paolo Manna on 14/08/2020.
//  Copyright © 2020 MongoDB. All rights reserved.
//

import Realm
import RealmSwift
import UIKit

class ProjectsViewController: UITableViewController, Storyboarded {
	weak var coordinator: MainCoordinator?
	
	var realm: Realm!
	var projects: Results<Project>!
	var notificationToken: NotificationToken?
	var partitionValue: ObjectId!
	
	@IBOutlet var logInOutButton: UIBarButtonItem!
	@IBOutlet var addButton: UIBarButtonItem!

	override func viewDidLoad() {
		super.viewDidLoad()
		
		logInOutButton						= UIBarButtonItem(title: "Log In", style: .plain, target: self, action: #selector(logOutButtonDidClick))
		navigationItem.leftBarButtonItem	= logInOutButton

		addButton							= UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(addButtonDidClick))
		addButton.isEnabled					= false
		navigationItem.rightBarButtonItem	= addButton
		
		tableView.tableFooterView	= UIView(frame: .zero)
	}
	
	// MARK: - Actions
    
	func loadFromDB() {
		let nav	= navigationController as? NavigationControllerWithError
		
		if realm == nil {
			guard let user = app.currentUser else {
				nav?.postErrorMessage(message: "Must be logged in to access this view", isError: true)
				
				return
			}
			let userIdentity = user.id
			
			partitionValue = try? ObjectId(string: userIdentity)
			guard partitionValue != nil else {
				nav?.postErrorMessage(message: "Couldn't get User ID to partition data", isError: true)
			   
				return
			}

			// Open a realm with the partition key set to the user.
			do {
				let config	= user.configuration(partitionValue: partitionValue)
				
				app.syncManager.errorHandler	= { [weak self] error, _ in
					let syncError = error as! SyncError
					
					switch syncError.code {
					case .clientResetError:
						if let (path, clientResetToken) = syncError.clientResetInfo() {
							DispatchQueue.main.async { [weak self] in
								let alertController = UIAlertController(title: "Client Reset",
								                                        message: "The database is out of sync, resetting client…",
								                                        preferredStyle: .alert)
								
								alertController.addAction(UIAlertAction(title: "Reset", style: .destructive, handler: { [weak self] _ -> Void in
									self?.realmBackup()
									self?.cleanupAndLogout()
									SyncSession.immediatelyHandleError(clientResetToken, syncManager: app.syncManager)
									self?.removeAutoGeneratedRealmBackup(path: path)
								}))
								self?.present(alertController, animated: true, completion: nil)
							}
						}
					default:
						print("SyncManager error: ", error.localizedDescription)
					}
				}
				realm = try Realm(configuration: config)
			} catch {
				nav?.postErrorMessage(message: error.localizedDescription, isError: true)
				
				return
			}
		}
		
		// Apply a backup file if found
		realmRestore()
		
		logInOutButton.title	= "Log Out"
		addButton.isEnabled		= true
		
		// Access all objects in the realm, sorted by _id so that the ordering is defined.
		projects = realm.objects(Project.self).sorted(byKeyPath: "_id")

		guard projects != nil else {
			nav?.postErrorMessage(message: "No projects found", isError: true)
			
			return
		}
		
		// Observe the projects for changes.
		notificationToken = projects.observe { [weak self] changes in
			guard let tableView = self?.tableView else { return }
			switch changes {
			case .initial:
				// Results are now populated and can be accessed without blocking the UI
				tableView.reloadData()
			case let .update(_, deletions, insertions, modifications):
				// Query results have changed, so apply them to the UITableView.
				tableView.beginUpdates()
				// It's important to be sure to always update a table in this order:
				// deletions, insertions, then updates. Otherwise, you could be unintentionally
				// updating at the wrong index!
				tableView.deleteRows(at: deletions.map { IndexPath(row: $0, section: 0) },
				                     with: .automatic)
				tableView.insertRows(at: insertions.map { IndexPath(row: $0, section: 0) },
				                     with: .automatic)
				tableView.reloadRows(at: modifications.map { IndexPath(row: $0, section: 0) },
				                     with: .automatic)
				tableView.endUpdates()
			case let .error(error):
				// An error occurred while opening the Realm file on the background worker thread
				nav?.postErrorMessage(message: error.localizedDescription, isError: true)
			}
		}
	}
	
	func removeAutoGeneratedRealmBackup(path: String) {
		do {
			try FileManager.default.removeItem(at: URL(fileURLWithPath: path))
		} catch {
			print("Error deleting backup path: \(path)")
		}
	}
	
	func realmBackup() {
		guard let realm = realm, let realmFileURL = realm.configuration.fileURL else { return }
		
		let backupURL	= realmFileURL.deletingPathExtension().appendingPathExtension("~realm")
		let fm			= FileManager.default
		
		do {
			// Delete file if present
			if fm.fileExists(atPath: backupURL.path) {
				try fm.removeItem(at: backupURL)
			}
			// Make a copy of the current realm
			try realm.writeCopy(toFile: backupURL)
			
			print("Realm backup successful")
		} catch {
			print("Realm backup failed: \(error.localizedDescription)")
		}
	}
	
	func realmRestore() {
		guard let realm = realm, let realmFileURL = realm.configuration.fileURL else {
			print("No realm to restore")
			return
		}

		let backupURL	= realmFileURL.deletingPathExtension().appendingPathExtension("~realm")
		let fm			= FileManager.default

		guard fm.fileExists(atPath: backupURL.path) else {
			print("No backup found at \(backupURL.lastPathComponent) to apply")
			return
		}
		
		let config = Realm.Configuration(fileURL: backupURL,
		                                 readOnly: true)
		
		guard let backupRealm = try? Realm(configuration: config) else {
			// Failed, clean backup file
			print("Error applying restore")
			try? fm.removeItem(at: backupURL)
			return
		}
		
		// This part needs to be tailored for the specific realm we're restoring
		let oldProjects	= backupRealm.objects(Project.self)
		
		do {
			try realm.write {
				// Reads all products, and applies changes
				for aProject in oldProjects {
					realm.create(Project.self, value: aProject, update: .modified)
				}
			}
			
			print("Restore successfully applied")
			try fm.removeItem(at: backupURL)
		} catch {
			print("Restore failed: \(error.localizedDescription)")
		}
	}

	func cleanupAndLogout() {
		notificationToken?.invalidate()
		notificationToken		= nil
		
		projects				= nil
		
		realm.invalidate()
		realm					= nil
		
		tableView.reloadData()
		
		logInOutButton.title	= "Log In"
		addButton.isEnabled		= false
		coordinator?.signOut()
	}
	
	@IBAction func logOutButtonDidClick() {
		if realm == nil {
			coordinator?.showLoginWindow()
		} else {
			let alertController = UIAlertController(title: "Log Out", message: "", preferredStyle: .alert)
			alertController.addAction(UIAlertAction(title: "Yes, Log Out", style: .destructive, handler: { _ -> Void in
				app.currentUser?.logOut(completion: { [weak self] _ in
					DispatchQueue.main.sync { [weak self] in
						self?.cleanupAndLogout()
					}
				})
			}))
			alertController.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
			present(alertController, animated: true, completion: nil)
		}
	}
    
	@IBAction func addButtonDidClick() {
		guard realm != nil else { return }
		
		// User clicked the add button.
        
		let alertController = UIAlertController(title: "Add Project", message: "", preferredStyle: .alert)

		alertController.addAction(UIAlertAction(title: "Save", style: .default, handler: { [weak self] _ -> Void in
			guard let self = self else { return }
			
			let textField = alertController.textFields![0] as UITextField
			let project = Project(partition: self.partitionValue, name: textField.text ?? "New Project")
                
			// All writes must happen in a write block.
			try! self.realm.write {
				self.realm.add(project)
			}
		}))
		alertController.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
		alertController.addTextField(configurationHandler: { (textField: UITextField!) -> Void in
			textField.placeholder = "New Project Name"
		})
		present(alertController, animated: true, completion: nil)
	}

	// MARK: - Table View

	override func numberOfSections(in tableView: UITableView) -> Int {
		return 1
	}

	override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		return projects?.count ?? 1
	}

	override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
		var cell: UITableViewCell!
		
		if let projects = projects, !projects.isEmpty {
			let project	= projects[indexPath.row]
		
			cell	= tableView.dequeueReusableCell(withIdentifier: "projectCell", for: indexPath)
		
			cell.textLabel!.text = project.name
		} else {
			cell	= tableView.dequeueReusableCell(withIdentifier: "noDataCell", for: indexPath)
		}
		return cell
	}

	override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
		// Return false if you do not want the specified item to be editable.
		if let projects = projects, !projects.isEmpty {
			return true
		}
		return false
	}

	override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
		guard editingStyle == .delete else { return }
		
		// The user can swipe to delete Projects.
		let project = projects[indexPath.row]
		
		// Delete all related tasks
		project.deleteRelatedTasks(in: realm)
		
		// All modifications must happen in a write block.
		try! realm.write {
			// Delete the project.
			realm.delete(project)
		}
	}
	
	override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
		tableView.deselectRow(at: indexPath, animated: true)
		
		if let user = app.currentUser, let projects = projects, !projects.isEmpty {
			let project		= projects[indexPath.row]
			guard let projectRealm = try? Realm(configuration: user.configuration(partitionValue: project._id)) else {
				(navigationController as? NavigationControllerWithError)?.postErrorMessage(message: "Cannot proceed to read project's tasks")
				
				return
			}
			
			coordinator?.showTasks(for: project, in: projectRealm)
		}
	}
}
